"""
api/routes/analyze.py

POST /analyze       - discharge PDF upload → multi-agent pipeline.
POST /analyze/text  - pre-extracted text (mobile on-device OCR) → same pipeline.
POST /analyze/image - OPT-IN enhanced scan: document photos → Gemini vision
                      transcription → same pipeline. The only route that ever
                      receives a photo; exists for handwriting the on-device
                      ML Kit path cannot read. Images stay in memory only.

Validation logic (_validate_uploaded_pdf) is the only non-trivial code here.
Everything else delegates: PDF storage to SessionStore, pipeline execution to
run_pipeline() via the shared _execute_pipeline helper, progress callbacks to
SessionStore, and simulator storage to SessionStore after the pipeline completes.
"""

import asyncio
import hashlib
import logging
import os
import tempfile
import uuid

from fastapi import (
    APIRouter,
    Depends,
    File,
    Form,
    HTTPException,
    Request,
    UploadFile,
)

from dischargeiq.api.middleware import sanitize_for_log, verify_api_key
from dischargeiq.api.routes.progress import cleanup_progress_after_delay
from dischargeiq.api.schemas import AnalyzeTextRequest
from dischargeiq.pipeline.orchestrator import run_pipeline
from dischargeiq.services.session import session_store
from dischargeiq.utils.pdf_token import mint_pdf_token
from dischargeiq.utils.vision_ocr import transcribe_document_images

logger = logging.getLogger(__name__)
router = APIRouter()

# ── Upload limits ─────────────────────────────────────────────────────────────
# 50 MB is well above a real discharge PDF (rarely > 5 MB with images) but
# low enough that a malicious upload cannot exhaust process memory.
_MAX_FILE_SIZE_MB = 50
_MAX_FILE_SIZE_BYTES = _MAX_FILE_SIZE_MB * 1024 * 1024
_PDF_MAGIC = b"%PDF"


def _resolve_session_id(request: Request) -> str:
    """
    Resolve the session id for an analyze request.

    Session ids are server-generated by default. A client hint via the
    X-Discharge-Session-Id header is accepted ONLY when (a) it is a valid
    UUID and (b) it maps to no existing session data or progress - a UUID
    already in use would let one client overwrite or observe another's
    session (session fixation). Clients send the hint so they can poll
    GET /progress/{id} for real per-agent updates DURING the run.

    Args:
        request: The incoming FastAPI request.

    Returns:
        str: A safe session id (client-proposed or freshly generated).
    """
    client_session_id = (request.headers.get("X-Discharge-Session-Id") or "").strip()
    try:
        proposed = str(uuid.UUID(client_session_id)) if client_session_id else None
    except ValueError:
        proposed = None
    if proposed and (
        session_store.get_pdf(proposed) is not None
        or session_store.get_progress(proposed) is not None
    ):
        logger.warning(
            "analyze - rejected X-Discharge-Session-Id %s: already in use", proposed
        )
        proposed = None
    return proposed or str(uuid.uuid4())


def validate_uploaded_pdf(filename: str, contents: bytes) -> None:
    """
    Validate uploaded file metadata and bytes for POST /analyze.

    Checks:
        1. Filename ends with .pdf (case-insensitive).
        2. Byte length does not exceed _MAX_FILE_SIZE_BYTES.
        3. First 4 bytes match the %PDF magic marker.

    Args:
        filename: Original uploaded filename from the client.
        contents: Raw uploaded file bytes.

    Raises:
        HTTPException 415: For non-PDF extension or invalid PDF signature.
        HTTPException 413: When payload exceeds the configured size cap.
    """
    if not filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=415, detail="Only PDF files are accepted.")
    if len(contents) > _MAX_FILE_SIZE_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"File exceeds {_MAX_FILE_SIZE_MB}MB limit.",
        )
    if not contents.startswith(_PDF_MAGIC):
        raise HTTPException(
            status_code=415,
            detail="File is not a valid PDF (magic bytes missing).",
        )


@router.post("/analyze", dependencies=[Depends(verify_api_key)])
async def analyze_discharge(
    request: Request,
    file: UploadFile = File(...),
    audience: str | None = Form(default=None),
):
    """
    Accept a discharge PDF upload and run the multi-agent pipeline.

    Stores the PDF in memory for later retrieval via GET /pdf/{session_id},
    runs the 6-agent pipeline, and returns a serialised PipelineResponse.
    The pipeline runs inside asyncio.wait_for (300s) - a timeout is surfaced
    as HTTP 504 so the UI can suggest trying a smaller PDF.

    Args:
        request: FastAPI Request - used to access app.state.db_pool.
        file:    PDF file uploaded by the patient or clinician.

    Returns:
        dict: PipelineResponse plus pdf_session_id for /pdf and /simulator fetches.

    Raises:
        HTTPException 413: File exceeds 50 MB.
        HTTPException 415: Not a PDF or invalid PDF magic bytes.
        HTTPException 504: Pipeline timed out (> 5 minutes).
        HTTPException 500: Unexpected pipeline error.
    """
    # Sanitize filename before any logging - raw filenames can contain newlines,
    # ANSI escape codes, or path separators that corrupt log entries.
    safe_filename = sanitize_for_log(file.filename or "")
    logger.info("POST /analyze - filename: %s", safe_filename)

    contents = await file.read()
    validate_uploaded_pdf(file.filename, contents)

    # Hash computed over in-memory bytes - avoids a second disk read after
    # the pipeline writes the tmpfile and all agents have run.
    document_hash = hashlib.sha256(contents).hexdigest()

    pdf_session_id = _resolve_session_id(request)

    session_store.set_progress(pdf_session_id, {
        "status": "running",
        "current_agent": 0,
        "agent_name": "Starting",
        "message": "Reading your document...",
    })
    session_store.store_pdf(contents, session_id=pdf_session_id)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp.write(contents)
        tmp_path = tmp.name

    db_pool = getattr(request.app.state, "db_pool", None)

    try:
        return await _execute_pipeline(
            doc_label=safe_filename,
            pdf_session_id=pdf_session_id,
            pdf_path=tmp_path,
            document_hash=document_hash,
            db_pool=db_pool,
            # Optional. The mobile app sends this when the document is filed
            # under a person whose age is known; everyone else omits it and
            # the pipeline infers the reader from the document text.
            audience=audience,
        )
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


# ── OCR text limits ───────────────────────────────────────────────────────────
# A one-page discharge summary is ~2–4k chars; 200k allows a very long
# multi-page scan while still bounding memory/token abuse. Below 100 chars a
# scan almost certainly failed - reject early with a clear message instead of
# burning 6 agent calls on noise.
_MIN_TEXT_CHARS = 100
_MAX_TEXT_CHARS = 200_000


@router.post("/analyze/text", dependencies=[Depends(verify_api_key)])
async def analyze_discharge_text(request: Request, body: AnalyzeTextRequest):
    """
    Run the multi-agent pipeline on pre-extracted document text.

    Sprint 2, Task 2.3 - the mobile OCR path: the phone recognizes text
    on-device (Google ML Kit) and sends ONLY the text, never the photo.
    That keeps images of paper documents off the wire and out of the
    backend entirely - a deliberate privacy property of the scan path.

    No PDF exists for this session, so GET /pdf/{session_id} will 404 -
    clients on the OCR path must not offer the "view original" affordance.

    Raises:
        HTTPException 422: Text too short (failed scan) or too long.
        HTTPException 504/500: Same semantics as POST /analyze.
    """
    text = body.text.strip()
    if len(text) < _MIN_TEXT_CHARS:
        raise HTTPException(
            status_code=422,
            detail="The scan captured too little text. Retake the photo with "
                   "the full page visible and good lighting.",
        )
    if len(text) > _MAX_TEXT_CHARS:
        raise HTTPException(status_code=422, detail="Scanned text is too long.")

    pdf_session_id = _resolve_session_id(request)
    logger.info(
        "POST /analyze/text - session: %s, chars: %d", pdf_session_id, len(text)
    )

    session_store.set_progress(pdf_session_id, {
        "status": "running",
        "current_agent": 0,
        "agent_name": "Starting",
        "message": "Reading your scanned document...",
    })

    return await _execute_pipeline(
        doc_label=f"ocr:{pdf_session_id}",
        pdf_session_id=pdf_session_id,
        pdf_path=f"ocr:{pdf_session_id}",  # label only - never opened
        document_hash=hashlib.sha256(text.encode("utf-8")).hexdigest(),
        db_pool=getattr(request.app.state, "db_pool", None),
        raw_text=text,
        # Same optional reader hint as POST /analyze - the scan path must not
        # lose caregiver voice just because the document arrived as text.
        audience=body.audience,
    )


# ── Enhanced scan (image) limits ──────────────────────────────────────────────
# One phone photo is 2-6 MB; 10 MB each and 10 pages bounds memory and vision
# token cost while covering any realistic discharge packet.
_MAX_IMAGE_PAGES = 10
_MAX_IMAGE_SIZE_BYTES = 10 * 1024 * 1024
_ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/heic", "image/webp"}


@router.post("/analyze/image", dependencies=[Depends(verify_api_key)])
async def analyze_discharge_image(
    request: Request,
    files: list[UploadFile] = File(...),
    audience: str | None = Form(default=None),
):
    """
    OPT-IN enhanced scan: transcribe document photos in the cloud, then run
    the standard pipeline on the transcription.

    Exists because on-device ML Kit cannot reliably read handwriting; Gemini
    vision can. The mobile app uses this ONLY when the patient explicitly
    chooses "enhanced read" after being told the photo will be uploaded -
    the default scan path remains on-device text extraction (/analyze/text).
    Photos are processed in memory and never persisted server-side.

    Raises:
        HTTPException 413: A photo exceeds the 10 MB cap.
        HTTPException 415: Not an accepted image type.
        HTTPException 422: Too many pages, or transcription yielded too
            little text to be a real document.
        HTTPException 502: Vision transcription failed after retries/failover.
        HTTPException 504/500: Same pipeline semantics as POST /analyze.
    """
    if not files or len(files) > _MAX_IMAGE_PAGES:
        raise HTTPException(
            status_code=422,
            detail=f"Send between 1 and {_MAX_IMAGE_PAGES} page photos.",
        )

    images: list[tuple[bytes, str]] = []
    for f in files:
        mime = (f.content_type or "").lower()
        if mime not in _ALLOWED_IMAGE_TYPES:
            raise HTTPException(
                status_code=415,
                detail="Only JPEG, PNG, HEIC, or WebP photos are accepted.",
            )
        raw = await f.read()
        if len(raw) > _MAX_IMAGE_SIZE_BYTES:
            raise HTTPException(status_code=413, detail="A photo exceeds the 10MB limit.")
        images.append((raw, mime))

    pdf_session_id = _resolve_session_id(request)
    logger.info(
        "POST /analyze/image - session: %s, pages: %d", pdf_session_id, len(images)
    )
    session_store.set_progress(pdf_session_id, {
        "status": "running",
        "current_agent": 0,
        "agent_name": "Starting",
        "message": "Reading your photographed document...",
    })

    try:
        # Sync vision calls run in a worker thread, one per page.
        text = await asyncio.to_thread(transcribe_document_images, images)
    except Exception as exc:
        logger.error("Vision transcription failed for %s: %s", pdf_session_id, exc)
        raise HTTPException(
            status_code=502,
            detail="Could not read the photos right now. Try the standard scan.",
        )

    # Same floor as /analyze/text: a near-empty transcription means the
    # photos were unreadable - reject before burning 6 agent calls.
    if len(text.strip()) < _MIN_TEXT_CHARS:
        raise HTTPException(
            status_code=422,
            detail="The photos could not be read. Retake them with the full "
                   "page visible and good lighting.",
        )

    return await _execute_pipeline(
        doc_label=f"enhanced-scan:{pdf_session_id}",
        pdf_session_id=pdf_session_id,
        pdf_path=f"enhanced-scan:{pdf_session_id}",  # label only - never opened
        document_hash=hashlib.sha256(text.encode("utf-8")).hexdigest(),
        db_pool=getattr(request.app.state, "db_pool", None),
        raw_text=text,
        audience=audience,
    )


async def _execute_pipeline(
    doc_label: str,
    pdf_session_id: str,
    pdf_path: str,
    document_hash: str,
    db_pool,
    raw_text: str | None = None,
    audience: str | None = None,
) -> dict:
    """
    Shared pipeline execution for both analyze routes.

    Owns the progress lifecycle (running → complete/error → delayed cleanup),
    simulator storage, and the timeout/error → HTTP status mapping. Both
    routes delegate here so the two input paths cannot drift apart.

    Args:
        doc_label: Sanitized name for log lines (filename or ocr:<session>).
        pdf_session_id: Session id already registered with the progress store.
        pdf_path: Tmpfile path (PDF route) or a label (text route).
        document_hash: SHA-256 of the source bytes/text.
        db_pool: Long-lived pool from app.state, or None.
        raw_text: Pre-extracted text for the OCR path; None for PDFs.

    Returns:
        dict: Serialised PipelineResponse plus pdf_session_id.

    Raises:
        HTTPException 504: Pipeline wall-clock timeout.
        HTTPException 500: Any other pipeline error.
    """
    # Identical document seen before (same hash): serve the cached result
    # under the NEW session id and skip all 7 LLM calls. Demo rehearsals and
    # repeat testing re-upload the same synthetic PDFs constantly - on the
    # Gemini free tier (20 requests/day) one cached repeat pays for itself.
    cached = session_store.get_result_for_hash(document_hash)
    if cached is not None:
        logger.info(
            "Analyze cache hit - '%s', hash: %.12s… (0 LLM calls)",
            doc_label, document_hash,
        )
        # A cached response carries the token minted for the ORIGINAL
        # session, and the token is deliberately session-bound - so reusing
        # it here would hand the caller a credential for someone else's
        # session id and 404 on their own. Re-mint for THIS session.
        #
        # Found by scripts/e2e_journey.py, which re-uploads the same document
        # and therefore hits the cache. No unit test would have: the bug only
        # exists in the interaction between two requests.
        _cache_token, _cache_exp = mint_pdf_token(pdf_session_id)
        result_dict = {
            **cached,
            "pdf_session_id": pdf_session_id,
            "pdf_token": _cache_token,
            "pdf_token_exp": _cache_exp,
            # Set here rather than inherited from `cached`. An entry cached by
            # a revision that predates this field has no hash, so during a
            # rolling deploy a cache hit would answer without one - and the
            # mobile client would create the duplicate library entry this
            # field exists to prevent. It is also simply the hash we just
            # looked the entry up by, so stating it cannot be wrong.
            "document_hash": document_hash,
        }
        if result_dict.get("patient_simulator") is not None:
            session_store.store_simulator(
                pdf_session_id, result_dict["patient_simulator"]
            )
        session_store.store_context(pdf_session_id, result_dict)
        session_store.set_progress(pdf_session_id, {
            "status": "complete",
            "current_agent": 7,
            "agent_name": "Complete",
            "message": "Almost ready...",
        })
        asyncio.create_task(cleanup_progress_after_delay(pdf_session_id))
        return result_dict

    try:
        def update_progress(agent_num: int, agent_name: str, message: str) -> None:
            session_store.set_progress(pdf_session_id, {
                "status": "running",
                "current_agent": agent_num,
                "agent_name": agent_name,
                "message": message,
            })

        result = await run_pipeline(
            pdf_path,
            session_id=pdf_session_id,
            on_progress=update_progress,
            document_hash=document_hash,
            db_pool=db_pool,
            raw_text=raw_text,
            audience_override=audience,
        )

        session_store.set_progress(pdf_session_id, {
            "status": "complete",
            "current_agent": 7,
            "agent_name": "Complete",
            "message": "Almost ready...",
        })
        asyncio.create_task(cleanup_progress_after_delay(pdf_session_id))

        logger.info(
            "Analyze complete - '%s', status: %s", doc_label, result.pipeline_status
        )

        result_dict = result.model_dump()
        result_dict["pdf_session_id"] = pdf_session_id

        # The identity of the DOCUMENT, as distinct from the session. Clients
        # need it to recognise a re-upload of a summary they already hold: the
        # mobile library keys ten stores off its own document id, so saving a
        # duplicate entry orphans the patient's appointment ticks, notes,
        # weights and corrected discharge date under the old id. Nothing
        # errors; it simply looks as though they never entered any of it.
        #
        # Deliberately the same hash this route already caches by, rather than
        # one the client computes for itself, so client and server can never
        # disagree about what "the same document" means.
        #
        # Set BEFORE store_result_for_hash below, so the cached copy carries
        # it too and a cache HIT returns the hash as well - the cache-hit path
        # builds its response from **cached.
        result_dict["document_hash"] = document_hash

        # Signed, short-lived access to this session's stored PDF. The
        # Streamlit viewer embeds the document in an <iframe>, which cannot
        # send an Authorization header, so the credential has to travel in
        # the URL - and therefore has to expire. Before this, the session id
        # alone fetched the document and never stopped working.
        pdf_token, pdf_token_exp = mint_pdf_token(pdf_session_id)
        result_dict["pdf_token"] = pdf_token
        result_dict["pdf_token_exp"] = pdf_token_exp

        if result.patient_simulator is not None:
            session_store.store_simulator(
                pdf_session_id, result.patient_simulator.model_dump()
            )

        # Cache the full response server-side so /chat can ground answers from
        # session_id alone - clients no longer re-send ~17KB of context per
        # chat message. Evicted/restarted sessions fall back to the client
        # sending pipeline_context (ChatRequest keeps the field as optional).
        session_store.store_context(pdf_session_id, result_dict)

        # Only successful runs are cacheable by hash: a cached "partial"
        # (transient LLM failure) or "rejected" would stick to the document
        # and block legitimate retries.
        if result.pipeline_status in ("complete", "complete_with_warnings"):
            session_store.store_result_for_hash(document_hash, result_dict)

        return result_dict

    except asyncio.TimeoutError:
        session_store.set_progress(pdf_session_id, {
            "status": "error",
            "current_agent": 0,
            "agent_name": "Timeout",
            "message": "Analysis timed out.",
        })
        asyncio.create_task(cleanup_progress_after_delay(pdf_session_id))
        logger.error("Pipeline timeout for document '%s'", doc_label)
        raise HTTPException(
            status_code=504,
            detail="Analysis took longer than 5 minutes. Please try a smaller or clearer PDF.",
        )
    except Exception as pipeline_error:
        session_store.set_progress(pdf_session_id, {
            "status": "error",
            "current_agent": 0,
            "agent_name": "Error",
            "message": "Analysis failed.",
        })
        asyncio.create_task(cleanup_progress_after_delay(pdf_session_id))
        logger.error("Pipeline error for '%s': %s", doc_label, pipeline_error)
        raise HTTPException(status_code=500, detail="Internal pipeline error.")
