#!/usr/bin/env python3
"""
scripts/check_media_drift.py

Report per-condition audio files whose source document has changed since the
audio was made. Owner: Likitha Shankar.

WHY THIS EXISTS
---------------
The five per-condition WAVs are generated BY HAND in NotebookLM from the
markdown in dischargeiq/media/sources/. Nothing links the two: editing a
source file changes what the audio is SUPPOSED to say and leaves the shipped
audio saying the old thing, silently and indefinitely.

That went from theoretical to real on 9 Sep 2026. The heart-failure explainer
told patients to call their doctor if they gained more than two pounds in a
day - the ACC/AHA figure, correct as general guidance - while the app was
simultaneously showing that patient the threshold from their OWN summary,
which on the demo document is three pounds and says GO TO THE ER TODAY. The
source was corrected to stop competing with the patient's own paperwork. The
WAV still says two pounds, and will until someone regenerates it in
NotebookLM.

A stale source is a documentation problem. A stale WAV is a patient hearing
clinical advice the team believes it has already removed, which is worse than
never having fixed it: the fix is recorded, so nobody looks again.

HOW IT WORKS
------------
A `.sha256` sidecar next to each WAV records the source hash the audio was
built from. No sidecar means the audio predates this check and cannot be
vouched for - reported as UNKNOWN, not as fine.

Usage:
  python scripts/check_media_drift.py            # report, exit 1 on drift
  python scripts/check_media_drift.py --accept   # after regenerating in
                                                 # NotebookLM, stamp current
"""

import argparse
import hashlib
import sys
from pathlib import Path

_MEDIA = Path(__file__).resolve().parent.parent / "dischargeiq" / "media"
_SOURCES = _MEDIA / "sources"


def _source_hash(path: Path) -> str:
    """SHA-256 of a source document, as the sidecar records it."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _sidecar(wav: Path) -> Path:
    return wav.with_suffix(".sha256")


def check() -> tuple[list[str], list[str], list[str]]:
    """
    Compare every source against the audio built from it.

    Returns:
        (drifted, unknown, current) - lists of condition names.
    """
    drifted: list[str] = []
    unknown: list[str] = []
    current: list[str] = []

    for source in sorted(_SOURCES.glob("*.md")):
        wav = _MEDIA / f"{source.stem}.wav"
        if not wav.exists():
            continue
        sidecar = _sidecar(wav)
        if not sidecar.exists():
            unknown.append(source.stem)
            continue
        if sidecar.read_text().strip() == _source_hash(source):
            current.append(source.stem)
        else:
            drifted.append(source.stem)
    return drifted, unknown, current


def accept() -> int:
    """Stamp every source's current hash, after regenerating the audio."""
    stamped = 0
    for source in sorted(_SOURCES.glob("*.md")):
        wav = _MEDIA / f"{source.stem}.wav"
        if not wav.exists():
            continue
        _sidecar(wav).write_text(_source_hash(source) + "\n")
        stamped += 1
    return stamped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--accept", action="store_true",
        help="Record current source hashes. Run ONLY after regenerating the "
             "audio in NotebookLM - it silently blesses whatever is there.",
    )
    args = parser.parse_args()

    if args.accept:
        print(f"stamped {accept()} audio file(s) as current")
        return 0

    drifted, unknown, current = check()
    for name in current:
        print(f"  ok        {name}")
    for name in unknown:
        print(f"  UNKNOWN   {name}  - no sidecar; cannot vouch for this audio")
    for name in drifted:
        print(f"  DRIFTED   {name}  - source changed since the audio was made")

    if drifted or unknown:
        print()
        print("Audio does not match its source. Regenerate the affected files")
        print("in NotebookLM from dischargeiq/media/sources/, then run:")
        print("  python scripts/check_media_drift.py --accept")
        print()
        print("Until then that audio should not reach a patient or a tester.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
