#!/usr/bin/env bash
#
# scripts/corpus_catchup.sh
#
# Fill in whatever the corpus run and the audio generation still owe, then
# refresh the accuracy report. Owner: Likitha Shankar.
#
# Written to be run unattended by cron, so it is IDEMPOTENT and SELF-LIMITING:
# when every document has an output and every diagnosis has an audio file, it
# logs "nothing to do" and exits without spending a single API call. That is
# what makes a daily schedule safe - it stops costing anything the day the
# work is finished, rather than needing someone to remember to remove it.
#
# Both jobs are quota-bound rather than time-bound:
#   - Vertex serves Gemini on DYNAMIC SHARED QUOTA: no per-project allowance,
#     no reset window, so 429s are capacity contention that comes and goes.
#     Pacing alone cannot outlast it, so the corpus step runs SMALL BATCHES IN
#     A LOOP WITH EXPONENTIAL BACKOFF and gives up after three consecutive
#     stalls rather than hammering a provider that is not serving us.
#   - Gemini TTS has a separate daily free-tier ceiling, so audio may fail
#     even when the corpus succeeds. Each is attempted independently.
#
# "Done" means every document has an output generated by the CURRENT prompts,
# not merely that a file exists. Outputs carry a prompt hash, and one made by
# superseded prompts counts as work still owed. Without that rule this job
# would have declared success on 25 Aug over 54 outputs describing the old
# system.
#
# Tunables (environment): BATCH (default 8), MAX_PASSES (default 12).
#
# It deliberately does NOT commit or push. A human reviews what it produced.
#
# Usage:
#   ./scripts/corpus_catchup.sh              # run now
#   crontab -l                               # see the schedule
#
# Logs land in logs/corpus_catchup/<date>.log (gitignored).

set -uo pipefail
cd "$(dirname "$0")/.."
REPO="$(pwd)"

PY="$REPO/.venv/bin/python3"
[ -x "$PY" ] || PY="$(command -v python3)"

LOG_DIR="$REPO/logs/corpus_catchup"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/$(date +%Y%m%d).log"
exec >> "$LOG" 2>&1

echo "=============================================================="
echo "corpus catch-up $(date '+%Y-%m-%d %H:%M:%S')"

export LLM_PROVIDER=vertex
export VERTEX_PROJECT=dischargeiq-502723
export VERTEX_LOCATION=us-central1
# No paid fallback on an unattended job: a Vertex outage must not silently
# start spending on Anthropic overnight.
export LLM_FALLBACK_PROVIDER=none

# How much is missing OR stale. "Stale" means the output exists but was made by
# prompts that have since changed: on 25 Aug 2026 three agent prompts changed
# and 54 outputs sat on disk looking complete while describing the old system.
# Counting only missing files would let this job report success over them.
todo() { "$PY" scripts/run_corpus_for_review.py --count-stale | cut -d' ' -f1; }

TODO="$(todo)"
echo "corpus documents missing or stale: $TODO"

if [ "$TODO" -gt 0 ]; then
  # Small batches with backoff, not one long run.
  #
  # Vertex serves Gemini on dynamic shared quota: there is no per-project
  # allowance and no reset window, so 429s are capacity contention that comes
  # and goes. A single long run cannot outlast it. Worse, the runner has a
  # circuit breaker that aborts after two consecutive documents fail, which is
  # correct behaviour - it stops the review set filling with unusable JSON -
  # but it means one invocation stops early and stays stopped. On 25 Aug a
  # --force run over 106 documents aborted after five, with 32 429s in four
  # minutes.
  #
  # So: run a small batch, see whether it moved, and back off when it did not.
  # Contention passes on its own, and a job that waits is worth more than a job
  # that hammers.
  PASS=0
  BACKOFF=60
  STALLS=0
  while [ "$TODO" -gt 0 ] && [ "$PASS" -lt "${MAX_PASSES:-12}" ]; do
    PASS=$((PASS + 1))
    echo "--- pass $PASS: $TODO left ---"

    # --stale, never --force: current outputs are skipped, so repeated passes
    # converge on zero instead of redoing finished work forever.
    "$PY" scripts/run_corpus_for_review.py --stale --limit "${BATCH:-8}" --delay 30 \
      || echo "  batch ended early (circuit breaker or quota) - continuing"

    AFTER="$(todo)"
    if [ "$AFTER" -lt "$TODO" ]; then
      # Progress: reset the backoff, capacity is available again.
      echo "  progress: $TODO -> $AFTER"
      STALLS=0
      BACKOFF=60
    else
      STALLS=$((STALLS + 1))
      echo "  no progress (stall $STALLS) - backing off ${BACKOFF}s"
      # Give up after three consecutive stalls rather than burning the night
      # on a provider that is not serving us. The job is resumable, so the
      # next scheduled run picks up exactly here.
      if [ "$STALLS" -ge 3 ]; then
        echo "  three stalls in a row - stopping. $AFTER still to do."
        echo "  This is contention, not a fault. Re-run later."
        break
      fi
      sleep "$BACKOFF"
      # Exponential, capped: doubling past ~8 minutes stops helping and just
      # delays the next real attempt.
      BACKOFF=$((BACKOFF * 2))
      [ "$BACKOFF" -gt 480 ] && BACKOFF=480
    fi
    TODO="$AFTER"
  done

  echo "corpus documents missing or stale after run: $TODO"
  # Only worth regenerating the report when the corpus is actually uniform.
  # A report built over a mix of old-prompt and new-prompt outputs measures
  # neither, and reads as though it measured both.
  if [ "$TODO" -eq 0 ]; then
    "$PY" scripts/corpus_accuracy_report.py
  else
    echo "skipping accuracy report: corpus is mixed, a report over it would"
    echo "blend old-prompt and new-prompt outputs and mean nothing"
  fi
else
  echo "corpus complete and current - no API calls made"
fi

# Per-case audio: one file per target diagnosis, generated from the most
# complete real analysis of that type. Separate quota, so attempt regardless.
AUDIO_TODO=0
for kind in heart_failure copd diabetes hip_replacement surgical; do
  [ -f "dischargeiq/media/$kind.wav" ] && continue
  AUDIO_TODO=1
  SRC="$("$PY" - "$kind" <<'PYEOF'
import glob, json, sys
want = sys.argv[1]
best, score = None, -1
for f in sorted(glob.glob('evaluation/corpus_outputs/mtsamples_*.json')):
    d = json.load(open(f))
    if d.get('document_type') != want or d.get('pipeline_status') == 'partial':
        continue
    s = sum(len(str(d.get(k) or '')) for k in
            ('diagnosis_explanation', 'medication_rationale',
             'recovery_trajectory', 'escalation_guide'))
    if s > score:
        best, score = f, s
print(best or '')
PYEOF
)"
  if [ -n "$SRC" ]; then
    echo "audio: $kind <- $SRC"
    "$PY" scripts/generate_case_audio.py "$SRC" || echo "  audio failed for $kind (quota?)"
    sleep 20
  else
    echo "audio: $kind has no usable source output yet"
  fi
done
[ "$AUDIO_TODO" -eq 0 ] && echo "all five audio files present - nothing to generate"

echo "done $(date '+%H:%M:%S')"
