# R8 rules for the release build.
#
# ML Kit text recognition: the app bundles ONLY the Latin recognizer
# (google_mlkit_text_recognition), but the plugin's initialize() references
# the Chinese/Devanagari/Japanese/Korean option classes so R8 fails the build
# on the missing script packs. The app never takes those code paths - Latin
# covers English discharge documents - so suppressing the warnings is safe.
# (Rules generated by AGP in build/.../missing_rules.txt.)
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
